### ISSUE TITLE
Make Hydra flake-based

### ISSUE THREAD

**Issue by edolstra** [tweag/nix#16]
Flakes remove the need for most Hydra jobset configuration, and for Hydra to fetch dependencies. A Hydra jobset only needs to specify a single flake reference (e.g. `github:my-org/my-project`). Hydra can then rely on Nix to fetch all flake dependencies.

Flakes should also expose a `provides.hydraJobs` attribute to tell Hydra what to build.

**Comment by CSVdB** [comment]
What needs to happen here exactly? It sounds like from the flakes side, this is already done. I.e. hydra can be given a FlakeRef, it can be checked whether the flake.nix file provides a "hydraJobs" attribute, and if so, that can be built and all dependencies will be fetched through the flake system.

I don't know how Hydra works though, there's probably some changes to be made there so you can pass FlakeRefs and it knows what to do?

**Comment by edolstra** [comment]
Implemented in https://github.com/NixOS/hydra/tree/flake and now live on https://hydra.nixos.org (see e.g. https://hydra.nixos.org/jobset/patchelf/master or https://hydra.nixos.org/jobset/nix/flakes).
